spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
app.documents.storage-dir=${APP_DOCUMENTS_STORAGE_DIR:./uploads/documents}
app.translation.deepl.api-key=c03149a5-213c-4a85-983f-6cad65cb18a5:fx
app.translation.deepl.base-url=${DEEPL_API_BASE_URL:https://api-free.deepl.com}
